### ISSUE TITLE
内部からアクセスすると504 Gateway Time-outする

### ISSUE THREAD

**Issue by fs-tkyk** [tokuhirom/Furl#126]
初めまして。
Nginx+fcgiwrapにて、ブラウザよりアクセスするプログラムを書いているのですが、
運用するhogehoge.com の内部から、同じhogehoge.com内にあるAPIを叩こうとするとTimeoutになります。

```
my $url = 'https://hogehoge.com/api/getData';
my $f = Furl->new();
my $res = $f->get($url);
print Dumper($res);
```

`$VAR1 = bless( { 'captured_req_content' => undef, 'headers' => bless( { 'x-internal-response' => [ 1 ], 'content-length' => [ 87 ] }, 'Furl::Headers' ), 'content' => 'Cannot read response header: timeout at *********.cgi line 18. ', 'request_src' => { 'headers' => undef, 'url' => 'https://hogehoge.com/api/getData', 'method' => 'GET' }, 'message' => 'Internal Response: Cannot read response header: timeout at *******.cgi line 18. ', 'captured_req_headers' => undef, 'minor_version' => 0, 'code' => 500 }, 'Furl::Response' );`

**urlを外のもの（例えば https://jlp.yahooapis.jp/～ みたい）にすると問題なくGETできます。
これは仕様なのでしょうか。それとも何か見落としがあるのでしょうか。
初心者的質問で申し訳ありませんが、ヒントを頂ければ助かります。

**Comment by mattn** [comment]
1. proxy をお使いですか？
2. curl で試すと動きますか？

```
$ curl https://hogehoge.com
```

**Comment by fs-tkyk** [comment]
早速のレスポンス有り難うございます。
Proxyは特に使っていません。
curlですと問題なくアクセス出来ます。Apache単体ですとうまくいっていた処理でしたが、今回Nginxでと思った所色々躓いてしまい…。
なお、AWS EC2のマシンです。セキュリティグループは、80,443を受け付けるようにしIP制限はしておりません。

**Comment by syohex** [comment]
Perlの他の HTTPクライアントモジュールを使った場合は問題は起きるのでしょうか ?
- https://metacpan.org/pod/HTTP::Tiny
- https://metacpan.org/pod/LWP

**Comment by fs-tkyk** [comment]
どちらも試して見ました。すると、やはりTimeoutが起きます。（外向きだとアクセス出来ました）
ということは、Furl起因ではないって事ですね…

**Comment by syohex** [comment]
`curl` での確認についてですが以下のように問題のプログラムから実行して確認されましたでしょうか ? 確認していない場合, この方法で問題が起きるかどうか確認いただけないでしょうか ?

```perl
my $res = `curl https://hogehoge.com/api/getData`;
print "$res"
```

**Comment by syohex** [comment]
もし環境変数に proxy関係(`http_proxy`, `https_proxy` etc)のものがあればそれらは unsetして確認いただければと思います.

**Comment by fs-tkyk** [comment]
curlを実行してくる結果は504 Gateway Time-outでした。
また、
`printenv | grep -i proxy
`
も空でした。

**Comment by syohex** [comment]
どのクライアントからでもタイムアウトしてしまうとするとネットワーク周りの問題でしょうか

**Comment by fs-tkyk** [comment]
皆様有り難うございます。皆様が寄り添ってヒントとなるよう導いて下さったので、原因が分かりました！

```
# vi /etc/sysconfig/spawn-fcgi
FCGI_SOCKET=/var/run/fcgiwrap.socket
FCGI_PROGRAM=/usr/sbin/fcgiwrap
FCGI_USER=nginx
FCGI_GROUP=nginx
FCGI_EXTRA_OPTIONS="-M 0776"
OPTIONS="-u $FCGI_USER -g $FCGI_GROUP -s $FCGI_SOCKET -S $FCGI_EXTRA_OPTIONS -F 2 -P /var/run/spawn-fcgi.pid -- $FCGI_PROGRAM -f"
```
オプション `-F 1` になっていたのを `-F 2` にしたところ無事動くようになりました！
これって、内部アクセスには2つchildが立つからでしょうかね…？

**Comment by syohex** [comment]
内部というのがよくわかっていなかったのですが(同一ネットワークからかと思っていた), サーバプログラムから自身に対してHTTPリクエストを出すという認識で良いでしょうか ? 

そうだとするとリクエストに対してプロセスが 1つしか作れないのでデッドロックになってしまいタイムアウトせざるを得ないということになってしまうかと思います.

- サーバは新規にプロセスを作成したいが上限にひっかかっておりプロセスの終了を待つ必要がある
- しかしただ一つのプロセスはサーバからレスポンスが返らないことには終了できない

双方が双方を待つ状態になってしまい先に進むことができず結果タイムアウトになってしまう, ということではないでしょうか.

**Comment by fs-tkyk** [comment]
はい、書き方が分かりにくくてすみません。同じサーバー上から自身に対してリクエストするとうまくいかないのが今回の困っていたことでした。分かってみれば、そりゃそうだなんですけど、一旦嵌まると駄目ですねorz
