### ISSUE TITLE
bug while request.

### ISSUE THREAD

**Issue by m-jackson** [tokuhirom/Furl#75]
Argument "318,318" isn't numeric in numeric ne (!=) at /usr/local/share/perl/5.14.2/Furl/HTTP.pm line 787.
Version of module 3.03

**Comment by kazuho** [comment]
Seems like RFC 7230 has clarified that implementations may try to rescue these kind of broken requests / responses.
https://github.com/plack/Plack/issues/493#issuecomment-71569544
