### ISSUE TITLE
"Keep-Alive" is no effect 

### ISSUE THREAD

**Issue by wahaha88** [tokuhirom/Furl#79]
In line 526 of Furl/HTTP.pm, FURL checks the HTTP response headers it gets from the server. It will read the Connection from the response header there, and compare the header value with the string keep-alive. The problem is that this does not take into account a different case of the response header. Some HTTP server returns a header value of Keep-Alive (mind the caps), so FURL does not recognize it properly.

I think the following change to Furl/HTTP.pm is more robust.
-    if ($connection_header eq 'keep-alive') {
-    if (lc($connection_header) eq 'keep-alive') {

**Comment by bissei** [comment]
+1 to fixing the problem.

**Comment by tokuhirom** [comment]
Please send me a p-r

**Comment by frioux** [comment]
Looks like this is fixed in 3.06.  Might wanna close it @tokuhirom

**Comment by syohex** [comment]
Please reopen if you have still this issue.
