### ISSUE TITLE
800_regression/01_capture_request.t Failing for Me

### ISSUE THREAD

**Issue by bluefeet** [tokuhirom/Furl#82]
This is an odd one.  Any thoughts?

```
#   Failed test at t/800_regression/01_capture_request.t line 10.
#          got: 'POST / HTTP/1.1
# Connection: keep-alive
# User-Agent: Furl::HTTP/3.05
# Host: www.mycompany.com
# 
# '
#     expected: undef

#   Failed test at t/800_regression/01_capture_request.t line 11.
#          got: ''
#     expected: undef
# Looks like you failed 2 tests of 2.
t/800_regression/01_capture_request.t ........... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
```

**Comment by bluefeet** [comment]
PS: I'm only able to reproduce this on a vagrant VM run via VirtualBox.  All other hosts don't seem to have this issue.

**Comment by bluefeet** [comment]
Looks like the issue is something on the VM's network setup where it resolves any non-resolvable DNS lookup to my company's production web site IP.  :-O

But, I would think you'd want this test to work even with odd DNS resolution setups.  This test isn't even testing DNS resolution, so how about using a fake IP address?  Like a TEST-NET address like `192.0.2.0` instead of `example.com.local`.

I tried it and the test now passes for me.

**Comment by bluefeet** [comment]
`my $r=$f->post("http://192.0.2.0");`

**Comment by syohex** [comment]
It's your environment issue. Please skip the test or ignore the test on such environment.
